name: Markdown Checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: |
            **/*.md
